version: '3.8'


services:
  db: 
   image: postgres:15
   container_name: postgres-db
   environment: 
    POSTGRES_USER: app
    POSTGRES_PASSWORD: 12345678
    POSTGRES_DB: app_db

   volumes: 
    - postgres_data:/var/lib/postgresql/data

   ports:
     - "5432:5432"
   networks:
     - app-network
  

  backend: 
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: backend-app
    environment:
      DATABASE_URL: postgres://app:12345678@db:5432/app_db
    depends_on:
     - db
    ports:
      - "8000:8000"
    networks:
     - app-network


  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile      
    container_name: frontend-app
    ports:
      - "3000:3000"
    networks:
     - app-network

networks:
   app-network:
    driver: bridge


volumes:
  postgres_data:
    driver: local


